const categories: string[] = [
  "Alcohol",
  "Charity",
  "Childcare",
  "Communication",
  "Credit",
  "Dining out",
  "Education",
  "Entertainment",
  "Fitness",
  "Celebrations",
  "Groceries",
  "Health",
  "Renovation",
  "Insurance",
  "Internet",
  "Investments",
  "Loan",
  "Mortgage",
  "Personal",
  "Pet Care",
  "Renovation",
  "Utilities",
  "Taxes",
  "Transport",
  "Travel",
  "Vehicle",
  "Other",
];

export default categories;
