const categories: string[] = [
  "Auto Maintenance",
  "Alcohol",
  "Charity",
  "Childcare",
  "Credit Payments",
  "Dining out",
  "Education",
  "Entertainment",
  "Fitness",
  "Celebrations",
  "Gas",
  "Groceries",
  "Health",
  "Home Improvements",
  "Insurance",
  "Internet",
  "Investments",
  "Mortgage",
  "Personal Purchases",
  "Pet Care",
  "Phone & Communication",
  "Utilities",
  "Taxes",
  "Transport",
  "Travel",
];

export default categories;
